# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitsurface <- function(x, y, groups, groups_ind, run_ls, pen_fact, lambda, gamma, shrinkage, lambda_step, pmax, gmax, active_set, active_set_count, sort, screen, eps, max_cd_iter, max_ls_iter, lips_const, loss_fun) {
    .Call(`_grpsel_fitsurface`, x, y, groups, groups_ind, run_ls, pen_fact, lambda, gamma, shrinkage, lambda_step, pmax, gmax, active_set, active_set_count, sort, screen, eps, max_cd_iter, max_ls_iter, lips_const, loss_fun)
}

lipschitz <- function(x, groups) {
    .Call(`_grpsel_lipschitz`, x, groups)
}

orthogonalise <- function(x, groups) {
    .Call(`_grpsel_orthogonalise`, x, groups)
}

unorthogonalise <- function(beta, groups, z) {
    .Call(`_grpsel_unorthogonalise`, beta, groups, z)
}

centers <- function(x) {
    .Call(`_grpsel_centers`, x)
}

scales <- function(x) {
    .Call(`_grpsel_scales`, x)
}

decenter <- function(x, center) {
    .Call(`_grpsel_decenter`, x, center)
}

descale <- function(x, scale) {
    .Call(`_grpsel_descale`, x, scale)
}

